server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: postgres://tfieogjnjbsyxn:4b22d9e9d0f6bd25e69c57eb039130032676194728dd8bdb75f12fcdd4f5f43c@ec2-52-0-114-209.compute-1.amazonaws.com:5432/d43kav5gpnu031
      username: tfieogjnjbsyxn
      password: 4b22d9e9d0f6bd25e69c57eb039130032676194728dd8bdb75f12fcdd4f5f43c

    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
          ddl-auto: none

application:
  description: Projeto criado para o Bootcamp DIO - Santander

